services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: customersdb
      MYSQL_USER: crmuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: ChangeIt@24

  crm-customer-app:
    container_name: crm-customer
    image: crm-app-image
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: crmuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb