apiVersion: v1
kind: Service
metadata:
  name: crm-mysql-service
spec:
  selector:
    app: {{ .Values.mysql.appname }}
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
