apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
        - name: crm-app
          image: crm-app-image:latest
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_HOST
              value: crm-mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: crmuser
            - name: MYSQL_PASSWORD
              value: ThePassword